-- 005_project_memory_repo_path.sql
-- Deprecated in V0.1 schema alignment: memory_repo_path is configured globally,
-- not stored per project. Kept as a no-op for fresh databases so migration
-- numbering remains stable.
